[build]
rustc-wrapper = "/home/vanius/.cargo/bin/sccache"
# target = "wasm32-unknown-unknown"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]
